version: '3.4'

networks:
        lan:
                external: false

services:
        nginx:
                container_name: nginx
                image: linuxserver/swag
                restart: always
                cap_add:
                        - NET_ADMIN
                networks:
                        - lan
                environment:
                        - PUID={{ uid }}
                        - PGID={{ gid }}
                        - TZ=US/Eastern
                        - URL={{ domain }}
                        - SUBDOMAINS={{ subdomain }}
                        - VALIDATION=http
                        - EMAIL={{ email }}
                        - DHLEVEL=2048
                        - ONLY_SUBDOMAINS={{ only_sub }}
                        - STAGING=false
                ports:
                        - 80:80
                        - 443:443
                volumes:
                        - ./nginx:/config
        
        xray:
                container_name: xray
                image: teddysun/xray
                restart: always
                networks:
                        - lan
                command: ["xray", "run", "-c", "/etc/xray/config.json"]
                volumes:
                        - ./Xray:/etc/xray
